server:
  port: 5050

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"

                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowed-headers: "*"
                exposed-headers:
                  - Authorization
                allow-credentials: true

          routes:
            - id: auth
              uri: http://localhost:3000
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: vehicle
              uri: http://localhost:5051
              predicates:
                - Path=/vehicle/**
              filters:
                - StripPrefix=1
